# Generated by Django 5.2.1 on 2025-06-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especime', models.CharField(default='desconhecido', max_length=100)),
                ('data_coleta', models.DateField(default='2025-01-01')),
            ],
        ),
    ]
